# Generated by Django 4.2.2 on 2023-06-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_alter_producto_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
