# Generated by Django 4.2.3 on 2023-07-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petscop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
