# Generated by Django 4.1.2 on 2023-06-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petscops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
