# Generated by Django 4.1.2 on 2023-06-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petscops', '0002_alter_clientes_edad'),
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombrep', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
